### ISSUE TITLE
How is this tool installed?

### ISSUE THREAD

**Issue by Hawpe** [l3v11/gclone#1]
Using `go get github.com/l3v11/gclone` doesn't work because `go get` is deprecated, and using `go install github.com/l3v11/gclone@latest` doesn't work either because of `replace` directives:

```
go install: github.com/l3v11/gclone@latest (in github.com/l3v11/gclone@v1.57.0-mod1.3.1):
	The go.mod file for the module providing named packages contains one or
	more replace directives. It must not contain directives that would cause
	it to be interpreted differently than if it were the main module.
```

**Comment by l3v11** [comment]
> Using `go get github.com/l3v11/gclone` doesn't work because `go get` is deprecated, and using `go install github.com/l3v11/gclone@latest` doesn't work either because of `replace` directives:
> 
> ```
> go install: github.com/l3v11/gclone@latest (in github.com/l3v11/gclone@v1.57.0-mod1.3.1):
> 	The go.mod file for the module providing named packages contains one or
> 	more replace directives. It must not contain directives that would cause
> 	it to be interpreted differently than if it were the main module.
> ```

Use the binary files, commits are being synced with rclone, so building own won't work until rclone-1.58.0 releases. 
You may try this - `go install github.com/l3v11/gclone@v1.57.0-mod1.3.1`

Binary files: https://github.com/l3v11/gclone/releases/tag/v1.57.0-mod1.3.1

**Comment by Hawpe** [comment]
I ended up using the binary files, thank you!
