### ISSUE TITLE
Feature request 

### ISSUE THREAD

**Issue by bolavefasfas** [l3v11/gclone#10]
Can you add a script that automatically detects the system and installs the package like 

1.  `sudo -v ; curl https://rclone.org/install.sh | sudo bash`
2.  `bash <(wget -qO- https://git.io/gclone.sh)`
In any format similar to this it would be easier to install then using script rather than downloading latest version its painful to check every time new update comes 
References 
`https://github.com/donwa/gclone#installation`

3. Add rotating sa support similar to this 
```
https://github.com/dogbutcat/gclone#4support-command-line-option---drive-rolling-sa-and---drive-rolling-count
https://github.com/dogbutcat/gclone#5support-command-line-option---drive-random-pick-sa
```

**Comment by bolavefasfas** [comment]
Any update ?

**Comment by l3v11** [comment]
Sorry but these won't be worked on.

**Comment by bolavefasfas** [comment]
Ok
