### ISSUE TITLE
404

### ISSUE THREAD

**Issue by vqoley** [l3v11/gclone#12]
everytime i try copy from google drive to google drive i got this error

"Failed to copy: googleapi: Error 404: File not found:"

found this [solution](https://forum.rclone.org/t/getting-googleapi-error-404-file-not-found-error-only-for-some-files-in-a-remote/30732/10) but it for rclone only. not gclone.

you may need integrate with like this https://beta.rclone.org/branch/fix-drive-resourcekey/v1.59.0-beta.6141.d206761d2.fix-drive-resourcekey/

**Comment by bolavefasfas** [comment]
+1

**Comment by l3v11** [comment]
I can't fix this since this issue is from rclone/googleapi. Better wait for them to fix it.
