### ISSUE TITLE
Cannot copy files to Google Drive

### ISSUE THREAD

**Issue by MOOnLyer** [l3v11/gclone#13]
It keeps rotating SA and no file is copied. I check the status of SA on Google side, and it is active.

The log is as followed:

> 2023-01-27 20:03:01 INFO  : Using sa file: /root/gclone/accounts/1.json
> 2023-01-27 20:03:01 INFO  : Using sa file: /root/gclone/accounts/2.json
> 2023-01-27 20:03:01 INFO  : Using sa file: /root/gclone/accounts/3.json
> 2023-01-27 20:03:03 INFO  : Using sa file: /root/gclone/accounts/4.json
> 2023-01-27 20:03:19 INFO  : Using sa file: /root/gclone/accounts/5.json
> 2023-01-27 20:03:35 INFO  : Using sa file: /root/gclone/accounts/6.json
> 2023-01-27 20:03:52 INFO  : Using sa file: /root/gclone/accounts/7.json
> 2023-01-27 20:04:08 INFO  : Using sa file: /root/gclone/accounts/8.json

The full command I use is `gclone copy -v -P "/downloads/AA" "GD:/AA"`

**Comment by l3v11** [comment]
Seems like your SAs are exhausted. Try again after 24 hours.

**Comment by MOOnLyer** [comment]
> Seems like your SAs are exhausted. Try again after 24 hours.

I doubt that is the case since I have 100 SAs, and I never transfer that many files. Actually, I did not upload anything to Google Drive in the last 24 hours.

**Comment by l3v11** [comment]
Can't help then, working fine for me

**Comment by MOOnLyer** [comment]
> Can't help then, working fine for me

It looks like it is coming from the shared drive I used. I could not upload a single thing either using web or gclone. X(

**Comment by areen-c** [comment]
> > Can't help then, working fine for me
> 
> It looks like it is coming from the shared drive I used. I could not upload a single thing either using web or gclone. X(

Google recently has a new policy limiting 100GB per shared drive, it's possible that your storage has exceeded the capacity of that policy.
