### ISSUE TITLE
Does this fork support SAs on mounts?

### ISSUE THREAD

**Issue by sjames272727** [l3v11/gclone#15]
I know that dogbutcat's fork of gclone does not support SAs on rclone mounts. Does this one? If not, are there plans to add that feature?

**Comment by l3v11** [comment]
No it does support SA on mount. But doesn't support automatic SA rotation on mount.

**Comment by lem6ns** [comment]
> No it does support SA on mount. But doesn't support automatic SA rotation on mount.

Is this planned in the future? Auto rotate SA on mount when upload limit

**Comment by l3v11** [comment]
No, it's not planned for now.

**Comment by bolavefasfas** [comment]
> No it does support SA on mount. But doesn't support automatic SA rotation on mount.

its possibe and very difficult as you have to write a bash script with execptions for almost every type of error that can occuer

its messy because of fuemount or else was easy 
I have made a script for transfering from gdrive sa to onedrive works continously 1000 sa no errors yet
