### ISSUE TITLE
Explanation of 'Shared Drive' quota (~20TB/drive/day) and 'file owner' quota (~2TB/day)

### ISSUE THREAD

**Issue by YenForYang** [l3v11/gclone#22]
I can't find any information on these 2 limitations. I've heard of the 750GB/day upload limit per account, and the 10TB limit.
I recently hit a `Error 403: The download quota for this file has been exceeded., downloadQuotaExceeded` when transferring files using accounts outside my organization (i.e. outside of my Workspace domain name, e.g. Gmail/Yahoo accounts). Transferring *with* an organization account works fine without error.

It appears that when I hit this error, all accounts not under my domain won't be able to download files and get the error 403 `downloadQuotaExceeded`.

I was wondering if I hit one of these limits, but I have no idea what the "shared drive" and "file owner" quota refer to.
Could anyone explain it to me? Thanks.

**Comment by l3v11** [comment]
Each file has 2TB/day download limit.

**Comment by YenForYang** [comment]
What about the 'Shared Drive' quota (~20TB/drive/day)? Is 20 TB the limit for downloading from a shared drive per day?

**Comment by l3v11** [comment]
Yes
