### ISSUE TITLE
Sync?

### ISSUE THREAD

**Issue by KuleshovEffect** [l3v11/gclone#25]
Does the sync command work with gclone, cycling SA accounts?
Or only the copy command?

**Comment by l3v11** [comment]
@KuleshovEffect Sync command works with gclone. But auto SA rotation feature won't work, only copy command works.

**Comment by KuleshovEffect** [comment]
I see, thank you.
Maybe consider making that more clear in the Readme?
The Features sections lead me believe everything worked.

When I use the `copy` command, I see `userRateLimitExceeded` errors in the log, but I don't see gclone trying to rotate through my three SA accounts. Any guess what I'm doing wrong?

```
[cgdsa01]
type = drive
client_id = {id}
client_secret = {secret}
scope = drive
service_account_file = ~/SA/1.json
team_drive = 0AMtRoP_aTdT6Uk9PVA
service_account_file_path = ~/SA/
root_folder_id = 
```

**Comment by l3v11** [comment]
Pass `-v` argument with your command and check the log. It should show if the SAs are rotating or not.
