### ISSUE TITLE
Change SA in use information

### ISSUE THREAD

**Issue by JoseAngelB** [l3v11/gclone#4]
Can you remove the line when a new SA is used? Or make it visible only when the -v(erbose) flag is used.
When the -P(rogress) flag is used, it does weird things

**Comment by l3v11** [comment]
@JoseAngelB What does it show?

**Comment by JoseAngelB** [comment]
https://i.imgur.com/c7oeXWB.png
When a new file is used, the message with the new SA used is shown by {--stats} time and is overwritten by the new progress information leaving behind some lines from the old progress

**Comment by l3v11** [comment]
> https://i.imgur.com/c7oeXWB.png When a new file is used, the message with the new SA used is shown by {--stats} time and is overwritten by the new progress information leaving behind some lines from the old progress

Send your full command, I'll test.

**Comment by JoseAngelB** [comment]
gclone.exe sync --track-renames --max-backlog 800000 --stats 5s --drive-server-side-across-configs -P "gd:{0AXXXXXXXXXXXXXXVA}" "gd:{0AXXXXXXXXXXXXXVA}"

**Comment by JoseAngelB** [comment]
I think it can be solved changing line 828
`fmt.Println( )`
by
`fs.Infof( )` or `fs.Debugf( )` if you want it with -v or -vv
(See https://github.com/rclone/rclone/blob/master/fs/log.go)

Sorry I can't compile it for testing

**Comment by l3v11** [comment]
> it does weird things

![IMG_20220418_102052](https://user-images.githubusercontent.com/57452819/163753991-9e2cc749-234d-464a-b30e-2baef45556cf.jpg)

You were talking about this issue, right?

**Comment by JoseAngelB** [comment]
Yes, it's the same.
I think the command -P removes the characters where it previously wrote and writes again.

**Comment by l3v11** [comment]
> Yes, it's the same. I think the command -P removes the characters where it previously wrote and writes again.

It switces random account after a while, so you'll get new stats, because old one gets stuck.

**Comment by JoseAngelB** [comment]
Tested with ` fmt.Println( )` and Added a pull request #5

**Comment by l3v11** [comment]
I've merged the PR. The binary files will be available on next rclone release. Thanks for opening the issue.
