### ISSUE TITLE
If using in a sandbox, different filesystem

### ISSUE THREAD

**Issue by z8512** [l3v11/gclone#6]
https://stackoverflow.com/questions/38959067/dns-lookup-issue-when-running-my-go-app-in-termux

**Comment by l3v11** [comment]
Not related with gclone

**Comment by z8512** [comment]
Related to the gclone build in arm device yes

**Comment by l3v11** [comment]
> Related to the gclone build in arm device yes

Try with rclone 1st, gclone is just a copy of rclone with SA rotation for Google drive.
