### ISSUE TITLE
Suggestion.. rotate the SA

### ISSUE THREAD

**Issue by fidodone** [l3v11/gclone#8]
It would be interesting if the gclone could rotate the SA to each file sent and not just switch SA when it reaches the 750gb Upload quota

Is it very difficult to put this kind of function?

**Comment by l3v11** [comment]
@fidodone
Can you describe why this function is needed?
Currently it doesn't have any issue with the rotation.

**Comment by fidodone** [comment]
> @fidodone Can you describe why this function is needed? Currently it doesn't have any issue with the rotation.

The idea would be that gclone could rotate the 'SA' for each file uploaded...
would be good even for those who send less than 750GB/day, because rotating the 'SA' would expand the download limit in the future

but I found a fork of gclone that does the rotation I suggested.
https://github.com/dogbutcat/gclone

**Comment by fidodone** [comment]
but I found a fork of gclone that does the rotation I suggested.
https://github.com/dogbutcat/gclone
