### ISSUE TITLE
Can you make a Script to install?

### ISSUE THREAD

**Issue by nguyenzzz** [l3v11/gclone#9]
I tried to install gclone with go but it doesn't work

**Comment by l3v11** [comment]
@nguyenzzz download the binary according to your system architecture from [Releases](https://github.com/l3v11/gclone/releases) section, no need to build yourself.

**Comment by nguyenzzz** [comment]
> @nguyenzzz download the binary according to your system architecture from [Releases](https://github.com/l3v11/gclone/releases) section, no need to build yourself.

Im new in linux. So i dont know to install it. Rclone has a script to install so it's easy for new user like me

**Comment by bolavefasfas** [comment]
> I tried to install gclone with go but it doesn't work
use this it will only work for ubuntu os I will add support to detect os and arc later works for me on my device try and let me know if it works 

```bash
wget https://dub.sh/gclone && sudo bash gclone
```

paste it in your ubuntu terminal
